// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface ModelInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModelInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_type = 1;</code>
   */
  java.lang.String getModelType();
  /**
   * <code>string model_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getModelTypeBytes();

  /**
   * <code>string model_name = 2;</code>
   */
  java.lang.String getModelName();
  /**
   * <code>string model_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <code>string target = 3;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
