package eu.more2020.visual.domain.GrpcAutoGenerated;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ClientCalls.asyncClientStreamingCall;
import static io.grpc.stub.ClientCalls.asyncServerStreamingCall;
import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.blockingServerStreamingCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ServerCalls.asyncClientStreamingCall;
import static io.grpc.stub.ServerCalls.asyncServerStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.15.0)",
    comments = "Source: forecasting.proto")
public final class RouteGuideGrpc {

  private RouteGuideGrpc() {}

  public static final String SERVICE_NAME = "RouteGuide";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo,
      eu.more2020.visual.domain.GrpcAutoGenerated.Status> getStartTrainingMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "StartTraining",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.Status.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo,
      eu.more2020.visual.domain.GrpcAutoGenerated.Status> getStartTrainingMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo, eu.more2020.visual.domain.GrpcAutoGenerated.Status> getStartTrainingMethod;
    if ((getStartTrainingMethod = RouteGuideGrpc.getStartTrainingMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getStartTrainingMethod = RouteGuideGrpc.getStartTrainingMethod) == null) {
          RouteGuideGrpc.getStartTrainingMethod = getStartTrainingMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo, eu.more2020.visual.domain.GrpcAutoGenerated.Status>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "StartTraining"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Status.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("StartTraining"))
                  .build();
          }
        }
     }
     return getStartTrainingMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
      eu.more2020.visual.domain.GrpcAutoGenerated.Progress> getGetProgressMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "GetProgress",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.JobID.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.Progress.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
      eu.more2020.visual.domain.GrpcAutoGenerated.Progress> getGetProgressMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID, eu.more2020.visual.domain.GrpcAutoGenerated.Progress> getGetProgressMethod;
    if ((getGetProgressMethod = RouteGuideGrpc.getGetProgressMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getGetProgressMethod = RouteGuideGrpc.getGetProgressMethod) == null) {
          RouteGuideGrpc.getGetProgressMethod = getGetProgressMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.JobID, eu.more2020.visual.domain.GrpcAutoGenerated.Progress>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "GetProgress"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.JobID.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Progress.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("GetProgress"))
                  .build();
          }
        }
     }
     return getGetProgressMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Target,
      eu.more2020.visual.domain.GrpcAutoGenerated.Results> getGetSpecificTargetResultsMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "GetSpecificTargetResults",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.Target.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.Results.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Target,
      eu.more2020.visual.domain.GrpcAutoGenerated.Results> getGetSpecificTargetResultsMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Target, eu.more2020.visual.domain.GrpcAutoGenerated.Results> getGetSpecificTargetResultsMethod;
    if ((getGetSpecificTargetResultsMethod = RouteGuideGrpc.getGetSpecificTargetResultsMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getGetSpecificTargetResultsMethod = RouteGuideGrpc.getGetSpecificTargetResultsMethod) == null) {
          RouteGuideGrpc.getGetSpecificTargetResultsMethod = getGetSpecificTargetResultsMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.Target, eu.more2020.visual.domain.GrpcAutoGenerated.Results>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "GetSpecificTargetResults"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Target.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Results.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("GetSpecificTargetResults"))
                  .build();
          }
        }
     }
     return getGetSpecificTargetResultsMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
      eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> getGetAllTargetsResultsMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "GetAllTargetsResults",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.JobID.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.AllResults.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
      eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> getGetAllTargetsResultsMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.JobID, eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> getGetAllTargetsResultsMethod;
    if ((getGetAllTargetsResultsMethod = RouteGuideGrpc.getGetAllTargetsResultsMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getGetAllTargetsResultsMethod = RouteGuideGrpc.getGetAllTargetsResultsMethod) == null) {
          RouteGuideGrpc.getGetAllTargetsResultsMethod = getGetAllTargetsResultsMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.JobID, eu.more2020.visual.domain.GrpcAutoGenerated.AllResults>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "GetAllTargetsResults"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.JobID.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.AllResults.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("GetAllTargetsResults"))
                  .build();
          }
        }
     }
     return getGetAllTargetsResultsMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp,
      eu.more2020.visual.domain.GrpcAutoGenerated.Inference> getGetInferenceMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "GetInference",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.Inference.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp,
      eu.more2020.visual.domain.GrpcAutoGenerated.Inference> getGetInferenceMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp, eu.more2020.visual.domain.GrpcAutoGenerated.Inference> getGetInferenceMethod;
    if ((getGetInferenceMethod = RouteGuideGrpc.getGetInferenceMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getGetInferenceMethod = RouteGuideGrpc.getGetInferenceMethod) == null) {
          RouteGuideGrpc.getGetInferenceMethod = getGetInferenceMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp, eu.more2020.visual.domain.GrpcAutoGenerated.Inference>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "GetInference"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Inference.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("GetInference"))
                  .build();
          }
        }
     }
     return getGetInferenceMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo,
      eu.more2020.visual.domain.GrpcAutoGenerated.Status> getSaveModelMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "SaveModel",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.Status.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo,
      eu.more2020.visual.domain.GrpcAutoGenerated.Status> getSaveModelMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo, eu.more2020.visual.domain.GrpcAutoGenerated.Status> getSaveModelMethod;
    if ((getSaveModelMethod = RouteGuideGrpc.getSaveModelMethod) == null) {
      synchronized (RouteGuideGrpc.class) {
        if ((getSaveModelMethod = RouteGuideGrpc.getSaveModelMethod) == null) {
          RouteGuideGrpc.getSaveModelMethod = getSaveModelMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo, eu.more2020.visual.domain.GrpcAutoGenerated.Status>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "RouteGuide", "SaveModel"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.Status.getDefaultInstance()))
                  .setSchemaDescriptor(new RouteGuideMethodDescriptorSupplier("SaveModel"))
                  .build();
          }
        }
     }
     return getSaveModelMethod;
  }

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static RouteGuideStub newStub(io.grpc.Channel channel) {
    return new RouteGuideStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static RouteGuideBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new RouteGuideBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static RouteGuideFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new RouteGuideFutureStub(channel);
  }

  /**
   */
  public static abstract class RouteGuideImplBase implements io.grpc.BindableService {

    /**
     * <pre>
     * Start training a model
     * Return: Start of training job
     * </pre>
     */
    public void startTraining(eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status> responseObserver) {
      asyncUnimplementedUnaryCall(getStartTrainingMethod(), responseObserver);
    }

    /**
     * <pre>
     * Get progress for a specific job 
     * Return: If the job is running, if it is done, or if it has not started yet
     * </pre>
     */
    public void getProgress(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Progress> responseObserver) {
      asyncUnimplementedUnaryCall(getGetProgressMethod(), responseObserver);
    }

    /**
     * <pre>
     * Get results for a specific target of a job
     * Return: Model evaluation metrics and predictions for the selected target
     * </pre>
     */
    public void getSpecificTargetResults(eu.more2020.visual.domain.GrpcAutoGenerated.Target request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Results> responseObserver) {
      asyncUnimplementedUnaryCall(getGetSpecificTargetResultsMethod(), responseObserver);
    }

    /**
     * <pre>
     * Get results for all targets of a job
     * Return: Model evaluation metrics and predictions for all targets
     * </pre>
     */
    public void getAllTargetsResults(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> responseObserver) {
      asyncUnimplementedUnaryCall(getGetAllTargetsResultsMethod(), responseObserver);
    }

    /**
     * <pre>
     * Get inference for a specific timestamp and model
     * Return: Predictions for a specific timestamp
     * </pre>
     */
    public void getInference(eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Inference> responseObserver) {
      asyncUnimplementedUnaryCall(getGetInferenceMethod(), responseObserver);
    }

    /**
     * <pre>
     * Save the desired model given the algorithm and the target
     * Return: If information was saved successfully
     * </pre>
     */
    public void saveModel(eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status> responseObserver) {
      asyncUnimplementedUnaryCall(getSaveModelMethod(), responseObserver);
    }

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            getStartTrainingMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo,
                eu.more2020.visual.domain.GrpcAutoGenerated.Status>(
                  this, METHODID_START_TRAINING)))
          .addMethod(
            getGetProgressMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
                eu.more2020.visual.domain.GrpcAutoGenerated.Progress>(
                  this, METHODID_GET_PROGRESS)))
          .addMethod(
            getGetSpecificTargetResultsMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.Target,
                eu.more2020.visual.domain.GrpcAutoGenerated.Results>(
                  this, METHODID_GET_SPECIFIC_TARGET_RESULTS)))
          .addMethod(
            getGetAllTargetsResultsMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.JobID,
                eu.more2020.visual.domain.GrpcAutoGenerated.AllResults>(
                  this, METHODID_GET_ALL_TARGETS_RESULTS)))
          .addMethod(
            getGetInferenceMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp,
                eu.more2020.visual.domain.GrpcAutoGenerated.Inference>(
                  this, METHODID_GET_INFERENCE)))
          .addMethod(
            getSaveModelMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo,
                eu.more2020.visual.domain.GrpcAutoGenerated.Status>(
                  this, METHODID_SAVE_MODEL)))
          .build();
    }
  }

  /**
   */
  public static final class RouteGuideStub extends io.grpc.stub.AbstractStub<RouteGuideStub> {
    private RouteGuideStub(io.grpc.Channel channel) {
      super(channel);
    }

    private RouteGuideStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected RouteGuideStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new RouteGuideStub(channel, callOptions);
    }

    /**
     * <pre>
     * Start training a model
     * Return: Start of training job
     * </pre>
     */
    public void startTraining(eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getStartTrainingMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     * <pre>
     * Get progress for a specific job 
     * Return: If the job is running, if it is done, or if it has not started yet
     * </pre>
     */
    public void getProgress(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Progress> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getGetProgressMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     * <pre>
     * Get results for a specific target of a job
     * Return: Model evaluation metrics and predictions for the selected target
     * </pre>
     */
    public void getSpecificTargetResults(eu.more2020.visual.domain.GrpcAutoGenerated.Target request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Results> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getGetSpecificTargetResultsMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     * <pre>
     * Get results for all targets of a job
     * Return: Model evaluation metrics and predictions for all targets
     * </pre>
     */
    public void getAllTargetsResults(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getGetAllTargetsResultsMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     * <pre>
     * Get inference for a specific timestamp and model
     * Return: Predictions for a specific timestamp
     * </pre>
     */
    public void getInference(eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Inference> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getGetInferenceMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     * <pre>
     * Save the desired model given the algorithm and the target
     * Return: If information was saved successfully
     * </pre>
     */
    public void saveModel(eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getSaveModelMethod(), getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class RouteGuideBlockingStub extends io.grpc.stub.AbstractStub<RouteGuideBlockingStub> {
    private RouteGuideBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private RouteGuideBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected RouteGuideBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new RouteGuideBlockingStub(channel, callOptions);
    }

    /**
     * <pre>
     * Start training a model
     * Return: Start of training job
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.Status startTraining(eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo request) {
      return blockingUnaryCall(
          getChannel(), getStartTrainingMethod(), getCallOptions(), request);
    }

    /**
     * <pre>
     * Get progress for a specific job 
     * Return: If the job is running, if it is done, or if it has not started yet
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.Progress getProgress(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request) {
      return blockingUnaryCall(
          getChannel(), getGetProgressMethod(), getCallOptions(), request);
    }

    /**
     * <pre>
     * Get results for a specific target of a job
     * Return: Model evaluation metrics and predictions for the selected target
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.Results getSpecificTargetResults(eu.more2020.visual.domain.GrpcAutoGenerated.Target request) {
      return blockingUnaryCall(
          getChannel(), getGetSpecificTargetResultsMethod(), getCallOptions(), request);
    }

    /**
     * <pre>
     * Get results for all targets of a job
     * Return: Model evaluation metrics and predictions for all targets
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.AllResults getAllTargetsResults(eu.more2020.visual.domain.GrpcAutoGenerated.JobID request) {
      return blockingUnaryCall(
          getChannel(), getGetAllTargetsResultsMethod(), getCallOptions(), request);
    }

    /**
     * <pre>
     * Get inference for a specific timestamp and model
     * Return: Predictions for a specific timestamp
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.Inference getInference(eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp request) {
      return blockingUnaryCall(
          getChannel(), getGetInferenceMethod(), getCallOptions(), request);
    }

    /**
     * <pre>
     * Save the desired model given the algorithm and the target
     * Return: If information was saved successfully
     * </pre>
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.Status saveModel(eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo request) {
      return blockingUnaryCall(
          getChannel(), getSaveModelMethod(), getCallOptions(), request);
    }
  }

  /**
   */
  public static final class RouteGuideFutureStub extends io.grpc.stub.AbstractStub<RouteGuideFutureStub> {
    private RouteGuideFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private RouteGuideFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected RouteGuideFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new RouteGuideFutureStub(channel, callOptions);
    }

    /**
     * <pre>
     * Start training a model
     * Return: Start of training job
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.Status> startTraining(
        eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo request) {
      return futureUnaryCall(
          getChannel().newCall(getStartTrainingMethod(), getCallOptions()), request);
    }

    /**
     * <pre>
     * Get progress for a specific job 
     * Return: If the job is running, if it is done, or if it has not started yet
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.Progress> getProgress(
        eu.more2020.visual.domain.GrpcAutoGenerated.JobID request) {
      return futureUnaryCall(
          getChannel().newCall(getGetProgressMethod(), getCallOptions()), request);
    }

    /**
     * <pre>
     * Get results for a specific target of a job
     * Return: Model evaluation metrics and predictions for the selected target
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.Results> getSpecificTargetResults(
        eu.more2020.visual.domain.GrpcAutoGenerated.Target request) {
      return futureUnaryCall(
          getChannel().newCall(getGetSpecificTargetResultsMethod(), getCallOptions()), request);
    }

    /**
     * <pre>
     * Get results for all targets of a job
     * Return: Model evaluation metrics and predictions for all targets
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.AllResults> getAllTargetsResults(
        eu.more2020.visual.domain.GrpcAutoGenerated.JobID request) {
      return futureUnaryCall(
          getChannel().newCall(getGetAllTargetsResultsMethod(), getCallOptions()), request);
    }

    /**
     * <pre>
     * Get inference for a specific timestamp and model
     * Return: Predictions for a specific timestamp
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.Inference> getInference(
        eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp request) {
      return futureUnaryCall(
          getChannel().newCall(getGetInferenceMethod(), getCallOptions()), request);
    }

    /**
     * <pre>
     * Save the desired model given the algorithm and the target
     * Return: If information was saved successfully
     * </pre>
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.Status> saveModel(
        eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo request) {
      return futureUnaryCall(
          getChannel().newCall(getSaveModelMethod(), getCallOptions()), request);
    }
  }

  private static final int METHODID_START_TRAINING = 0;
  private static final int METHODID_GET_PROGRESS = 1;
  private static final int METHODID_GET_SPECIFIC_TARGET_RESULTS = 2;
  private static final int METHODID_GET_ALL_TARGETS_RESULTS = 3;
  private static final int METHODID_GET_INFERENCE = 4;
  private static final int METHODID_SAVE_MODEL = 5;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final RouteGuideImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(RouteGuideImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_START_TRAINING:
          serviceImpl.startTraining((eu.more2020.visual.domain.GrpcAutoGenerated.TrainingInfo) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status>) responseObserver);
          break;
        case METHODID_GET_PROGRESS:
          serviceImpl.getProgress((eu.more2020.visual.domain.GrpcAutoGenerated.JobID) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Progress>) responseObserver);
          break;
        case METHODID_GET_SPECIFIC_TARGET_RESULTS:
          serviceImpl.getSpecificTargetResults((eu.more2020.visual.domain.GrpcAutoGenerated.Target) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Results>) responseObserver);
          break;
        case METHODID_GET_ALL_TARGETS_RESULTS:
          serviceImpl.getAllTargetsResults((eu.more2020.visual.domain.GrpcAutoGenerated.JobID) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.AllResults>) responseObserver);
          break;
        case METHODID_GET_INFERENCE:
          serviceImpl.getInference((eu.more2020.visual.domain.GrpcAutoGenerated.Timestamp) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Inference>) responseObserver);
          break;
        case METHODID_SAVE_MODEL:
          serviceImpl.saveModel((eu.more2020.visual.domain.GrpcAutoGenerated.ModelInfo) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.Status>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static abstract class RouteGuideBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
    RouteGuideBaseDescriptorSupplier() {}

    @java.lang.Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.GrpcProto.getDescriptor();
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
      return getFileDescriptor().findServiceByName("RouteGuide");
    }
  }

  private static final class RouteGuideFileDescriptorSupplier
      extends RouteGuideBaseDescriptorSupplier {
    RouteGuideFileDescriptorSupplier() {}
  }

  private static final class RouteGuideMethodDescriptorSupplier
      extends RouteGuideBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
    private final String methodName;

    RouteGuideMethodDescriptorSupplier(String methodName) {
      this.methodName = methodName;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
      return getServiceDescriptor().findMethodByName(methodName);
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (RouteGuideGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new RouteGuideFileDescriptorSupplier())
              .addMethod(getStartTrainingMethod())
              .addMethod(getGetProgressMethod())
              .addMethod(getGetSpecificTargetResultsMethod())
              .addMethod(getGetAllTargetsResultsMethod())
              .addMethod(getGetInferenceMethod())
              .addMethod(getSaveModelMethod())
              .build();
        }
      }
    }
    return result;
  }
}
