// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string model_name = 2;</code>
   * @return The modelName.
   */
  java.lang.String getModelName();
  /**
   * <code>string model_name = 2;</code>
   * @return The bytes for modelName.
   */
  com.google.protobuf.ByteString
      getModelNameBytes();

  /**
   * <code>string kind = 3;</code>
   * @return The kind.
   */
  java.lang.String getKind();
  /**
   * <code>string kind = 3;</code>
   * @return The bytes for kind.
   */
  com.google.protobuf.ByteString
      getKindBytes();
}
