// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>string model_name = 2;</code>
   */
  java.lang.String getModelName();
  /**
   * <code>string model_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getModelNameBytes();
}
