// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated;

public interface TrainingInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrainingInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string config = 2;</code>
   */
  java.lang.String getConfig();
  /**
   * <code>string config = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfigBytes();
}
