package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ClientCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ClientCalls.asyncClientStreamingCall;
import static io.grpc.stub.ClientCalls.asyncServerStreamingCall;
import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.blockingServerStreamingCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.stub.ServerCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ServerCalls.asyncClientStreamingCall;
import static io.grpc.stub.ServerCalls.asyncServerStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.15.0)",
    comments = "Source: tools.proto")
public final class DataServiceGrpc {

  private DataServiceGrpc() {}

  public static final String SERVICE_NAME = "grpc.DataService";

  // Static method descriptors that strictly reflect the proto.
  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> getGetDatasetDataMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "GetDatasetData",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> getGetDatasetDataMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> getGetDatasetDataMethod;
    if ((getGetDatasetDataMethod = DataServiceGrpc.getGetDatasetDataMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getGetDatasetDataMethod = DataServiceGrpc.getGetDatasetDataMethod) == null) {
          DataServiceGrpc.getGetDatasetDataMethod = getGetDatasetDataMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "GetDatasetData"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("GetDatasetData"))
                  .build();
          }
        }
     }
     return getGetDatasetDataMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> getCheckWashesMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "CheckWashes",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> getCheckWashesMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> getCheckWashesMethod;
    if ((getCheckWashesMethod = DataServiceGrpc.getCheckWashesMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getCheckWashesMethod = DataServiceGrpc.getCheckWashesMethod) == null) {
          DataServiceGrpc.getCheckWashesMethod = getCheckWashesMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "CheckWashes"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("CheckWashes"))
                  .build();
          }
        }
     }
     return getCheckWashesMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> getCPDetectionMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "CPDetection",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> getCPDetectionMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> getCPDetectionMethod;
    if ((getCPDetectionMethod = DataServiceGrpc.getCPDetectionMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getCPDetectionMethod = DataServiceGrpc.getCPDetectionMethod) == null) {
          DataServiceGrpc.getCPDetectionMethod = getCPDetectionMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "CPDetection"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("CPDetection"))
                  .build();
          }
        }
     }
     return getCPDetectionMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> getExtractRainsMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "ExtractRains",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> getExtractRainsMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> getExtractRainsMethod;
    if ((getExtractRainsMethod = DataServiceGrpc.getExtractRainsMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getExtractRainsMethod = DataServiceGrpc.getExtractRainsMethod) == null) {
          DataServiceGrpc.getExtractRainsMethod = getExtractRainsMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "ExtractRains"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("ExtractRains"))
                  .build();
          }
        }
     }
     return getExtractRainsMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> getCalculatePowerIndexMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "CalculatePowerIndex",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> getCalculatePowerIndexMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> getCalculatePowerIndexMethod;
    if ((getCalculatePowerIndexMethod = DataServiceGrpc.getCalculatePowerIndexMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getCalculatePowerIndexMethod = DataServiceGrpc.getCalculatePowerIndexMethod) == null) {
          DataServiceGrpc.getCalculatePowerIndexMethod = getCalculatePowerIndexMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "CalculatePowerIndex"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("CalculatePowerIndex"))
                  .build();
          }
        }
     }
     return getCalculatePowerIndexMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> getForecastingMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "Forecasting",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> getForecastingMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> getForecastingMethod;
    if ((getForecastingMethod = DataServiceGrpc.getForecastingMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getForecastingMethod = DataServiceGrpc.getForecastingMethod) == null) {
          DataServiceGrpc.getForecastingMethod = getForecastingMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "Forecasting"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("Forecasting"))
                  .build();
          }
        }
     }
     return getForecastingMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> getEstimateYawMisalignmentMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "EstimateYawMisalignment",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> getEstimateYawMisalignmentMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> getEstimateYawMisalignmentMethod;
    if ((getEstimateYawMisalignmentMethod = DataServiceGrpc.getEstimateYawMisalignmentMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getEstimateYawMisalignmentMethod = DataServiceGrpc.getEstimateYawMisalignmentMethod) == null) {
          DataServiceGrpc.getEstimateYawMisalignmentMethod = getEstimateYawMisalignmentMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "EstimateYawMisalignment"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("EstimateYawMisalignment"))
                  .build();
          }
        }
     }
     return getEstimateYawMisalignmentMethod;
  }

  private static volatile io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> getFrechetMethod;

  @io.grpc.stub.annotations.RpcMethod(
      fullMethodName = SERVICE_NAME + '/' + "Frechet",
      requestType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest.class,
      responseType = eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse.class,
      methodType = io.grpc.MethodDescriptor.MethodType.UNARY)
  public static io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest,
      eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> getFrechetMethod() {
    io.grpc.MethodDescriptor<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> getFrechetMethod;
    if ((getFrechetMethod = DataServiceGrpc.getFrechetMethod) == null) {
      synchronized (DataServiceGrpc.class) {
        if ((getFrechetMethod = DataServiceGrpc.getFrechetMethod) == null) {
          DataServiceGrpc.getFrechetMethod = getFrechetMethod = 
              io.grpc.MethodDescriptor.<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest, eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse>newBuilder()
              .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
              .setFullMethodName(generateFullMethodName(
                  "grpc.DataService", "Frechet"))
              .setSampledToLocalTracing(true)
              .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest.getDefaultInstance()))
              .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
                  eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse.getDefaultInstance()))
                  .setSchemaDescriptor(new DataServiceMethodDescriptorSupplier("Frechet"))
                  .build();
          }
        }
     }
     return getFrechetMethod;
  }

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static DataServiceStub newStub(io.grpc.Channel channel) {
    return new DataServiceStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static DataServiceBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new DataServiceBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static DataServiceFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new DataServiceFutureStub(channel);
  }

  /**
   */
  public static abstract class DataServiceImplBase implements io.grpc.BindableService {

    /**
     */
    public void getDatasetData(eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getGetDatasetDataMethod(), responseObserver);
    }

    /**
     */
    public void checkWashes(eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getCheckWashesMethod(), responseObserver);
    }

    /**
     */
    public void cPDetection(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getCPDetectionMethod(), responseObserver);
    }

    /**
     */
    public void extractRains(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getExtractRainsMethod(), responseObserver);
    }

    /**
     */
    public void calculatePowerIndex(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getCalculatePowerIndexMethod(), responseObserver);
    }

    /**
     */
    public void forecasting(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getForecastingMethod(), responseObserver);
    }

    /**
     */
    public void estimateYawMisalignment(eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getEstimateYawMisalignmentMethod(), responseObserver);
    }

    /**
     */
    public void frechet(eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> responseObserver) {
      asyncUnimplementedUnaryCall(getFrechetMethod(), responseObserver);
    }

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            getGetDatasetDataMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse>(
                  this, METHODID_GET_DATASET_DATA)))
          .addMethod(
            getCheckWashesMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse>(
                  this, METHODID_CHECK_WASHES)))
          .addMethod(
            getCPDetectionMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse>(
                  this, METHODID_CPDETECTION)))
          .addMethod(
            getExtractRainsMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse>(
                  this, METHODID_EXTRACT_RAINS)))
          .addMethod(
            getCalculatePowerIndexMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse>(
                  this, METHODID_CALCULATE_POWER_INDEX)))
          .addMethod(
            getForecastingMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse>(
                  this, METHODID_FORECASTING)))
          .addMethod(
            getEstimateYawMisalignmentMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse>(
                  this, METHODID_ESTIMATE_YAW_MISALIGNMENT)))
          .addMethod(
            getFrechetMethod(),
            asyncUnaryCall(
              new MethodHandlers<
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest,
                eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse>(
                  this, METHODID_FRECHET)))
          .build();
    }
  }

  /**
   */
  public static final class DataServiceStub extends io.grpc.stub.AbstractStub<DataServiceStub> {
    private DataServiceStub(io.grpc.Channel channel) {
      super(channel);
    }

    private DataServiceStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected DataServiceStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new DataServiceStub(channel, callOptions);
    }

    /**
     */
    public void getDatasetData(eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getGetDatasetDataMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void checkWashes(eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getCheckWashesMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void cPDetection(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getCPDetectionMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void extractRains(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getExtractRainsMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void calculatePowerIndex(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getCalculatePowerIndexMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void forecasting(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getForecastingMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void estimateYawMisalignment(eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getEstimateYawMisalignmentMethod(), getCallOptions()), request, responseObserver);
    }

    /**
     */
    public void frechet(eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest request,
        io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(getFrechetMethod(), getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class DataServiceBlockingStub extends io.grpc.stub.AbstractStub<DataServiceBlockingStub> {
    private DataServiceBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private DataServiceBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected DataServiceBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new DataServiceBlockingStub(channel, callOptions);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse getDatasetData(eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest request) {
      return blockingUnaryCall(
          getChannel(), getGetDatasetDataMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse checkWashes(eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest request) {
      return blockingUnaryCall(
          getChannel(), getCheckWashesMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse cPDetection(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest request) {
      return blockingUnaryCall(
          getChannel(), getCPDetectionMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse extractRains(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest request) {
      return blockingUnaryCall(
          getChannel(), getExtractRainsMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse calculatePowerIndex(eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest request) {
      return blockingUnaryCall(
          getChannel(), getCalculatePowerIndexMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse forecasting(eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest request) {
      return blockingUnaryCall(
          getChannel(), getForecastingMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse estimateYawMisalignment(eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest request) {
      return blockingUnaryCall(
          getChannel(), getEstimateYawMisalignmentMethod(), getCallOptions(), request);
    }

    /**
     */
    public eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse frechet(eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest request) {
      return blockingUnaryCall(
          getChannel(), getFrechetMethod(), getCallOptions(), request);
    }
  }

  /**
   */
  public static final class DataServiceFutureStub extends io.grpc.stub.AbstractStub<DataServiceFutureStub> {
    private DataServiceFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private DataServiceFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected DataServiceFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new DataServiceFutureStub(channel, callOptions);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse> getDatasetData(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getGetDatasetDataMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse> checkWashes(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getCheckWashesMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse> cPDetection(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getCPDetectionMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse> extractRains(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getExtractRainsMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse> calculatePowerIndex(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getCalculatePowerIndexMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse> forecasting(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getForecastingMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse> estimateYawMisalignment(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getEstimateYawMisalignmentMethod(), getCallOptions()), request);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse> frechet(
        eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest request) {
      return futureUnaryCall(
          getChannel().newCall(getFrechetMethod(), getCallOptions()), request);
    }
  }

  private static final int METHODID_GET_DATASET_DATA = 0;
  private static final int METHODID_CHECK_WASHES = 1;
  private static final int METHODID_CPDETECTION = 2;
  private static final int METHODID_EXTRACT_RAINS = 3;
  private static final int METHODID_CALCULATE_POWER_INDEX = 4;
  private static final int METHODID_FORECASTING = 5;
  private static final int METHODID_ESTIMATE_YAW_MISALIGNMENT = 6;
  private static final int METHODID_FRECHET = 7;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final DataServiceImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(DataServiceImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_GET_DATASET_DATA:
          serviceImpl.getDatasetData((eu.more2020.visual.domain.GrpcAutoGenerated.tools.GetDatasetDataRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.DatasetDataResponse>) responseObserver);
          break;
        case METHODID_CHECK_WASHES:
          serviceImpl.checkWashes((eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.WashesResponse>) responseObserver);
          break;
        case METHODID_CPDETECTION:
          serviceImpl.cPDetection((eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CPDetectionResponse>) responseObserver);
          break;
        case METHODID_EXTRACT_RAINS:
          serviceImpl.extractRains((eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ExtractRainsResponse>) responseObserver);
          break;
        case METHODID_CALCULATE_POWER_INDEX:
          serviceImpl.calculatePowerIndex((eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.CalculatePowerIndexResponse>) responseObserver);
          break;
        case METHODID_FORECASTING:
          serviceImpl.forecasting((eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.ForecastingResponse>) responseObserver);
          break;
        case METHODID_ESTIMATE_YAW_MISALIGNMENT:
          serviceImpl.estimateYawMisalignment((eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.EstimateYawMisalignmentResponse>) responseObserver);
          break;
        case METHODID_FRECHET:
          serviceImpl.frechet((eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetRequest) request,
              (io.grpc.stub.StreamObserver<eu.more2020.visual.domain.GrpcAutoGenerated.tools.FrechetResponse>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static abstract class DataServiceBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoFileDescriptorSupplier, io.grpc.protobuf.ProtoServiceDescriptorSupplier {
    DataServiceBaseDescriptorSupplier() {}

    @java.lang.Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return eu.more2020.visual.domain.GrpcAutoGenerated.tools.GrpcProto.getDescriptor();
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.ServiceDescriptor getServiceDescriptor() {
      return getFileDescriptor().findServiceByName("DataService");
    }
  }

  private static final class DataServiceFileDescriptorSupplier
      extends DataServiceBaseDescriptorSupplier {
    DataServiceFileDescriptorSupplier() {}
  }

  private static final class DataServiceMethodDescriptorSupplier
      extends DataServiceBaseDescriptorSupplier
      implements io.grpc.protobuf.ProtoMethodDescriptorSupplier {
    private final String methodName;

    DataServiceMethodDescriptorSupplier(String methodName) {
      this.methodName = methodName;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.MethodDescriptor getMethodDescriptor() {
      return getServiceDescriptor().findMethodByName(methodName);
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (DataServiceGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new DataServiceFileDescriptorSupplier())
              .addMethod(getGetDatasetDataMethod())
              .addMethod(getCheckWashesMethod())
              .addMethod(getCPDetectionMethod())
              .addMethod(getExtractRainsMethod())
              .addMethod(getCalculatePowerIndexMethod())
              .addMethod(getForecastingMethod())
              .addMethod(getEstimateYawMisalignmentMethod())
              .addMethod(getFrechetMethod())
              .build();
        }
      }
    }
    return result;
  }
}
