// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface EstimateYawMisalignmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.EstimateYawMisalignmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataset_id = 1;</code>
   */
  java.lang.String getDatasetId();
  /**
   * <code>string dataset_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();

  /**
   * <code>string start_date = 2;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string start_date = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string end_date = 3;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string end_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();

  /**
   * <code>int32 window = 4;</code>
   */
  int getWindow();

  /**
   * <code>bool query_modelar = 5;</code>
   */
  boolean getQueryModelar();
}
