// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface ForecastingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ForecastingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
