// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface FrechetCalculatorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.FrechetCalculatorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataset_id = 1;</code>
   */
  java.lang.String getDatasetId();
  /**
   * <code>string dataset_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();

  /**
   * <code>string start_date = 2;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string start_date = 2;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string end_date = 3;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string end_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();

  /**
   * <code>int32 R = 4;</code>
   */
  int getR();

  /**
   * <code>int32 W = 5;</code>
   */
  int getW();

  /**
   * <code>string column = 6;</code>
   */
  java.lang.String getColumn();
  /**
   * <code>string column = 6;</code>
   */
  com.google.protobuf.ByteString
      getColumnBytes();
}
