// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public final class GrpcProto {
  private GrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetDatasetDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetDatasetDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DatasetDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DatasetDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WashesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WashesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WashesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WashesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPDetectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CPDetectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPDetectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CPDetectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExtractRainsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExtractRainsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExtractRainsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExtractRainsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatePowerIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculatePowerIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatePowerIndexResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculatePowerIndexResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForecastingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForecastingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForecastingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForecastingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EstimateYawMisalignmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EstimateYawMisalignmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EstimateYawMisalignmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EstimateYawMisalignmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FrechetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FrechetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FrechetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FrechetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013tools.proto\"(\n\025GetDatasetDataRequest\022\017" +
      "\n\007data_id\030\001 \001(\t\"#\n\023DatasetDataResponse\022\014" +
      "\n\004data\030\001 \001(\t\"#\n\rWashesRequest\022\022\n\ndataset" +
      "_id\030\001 \001(\t\" \n\016WashesResponse\022\016\n\006washes\030\001 " +
      "\001(\t\"\271\001\n\022CPDetectionRequest\022\022\n\ndataset_id" +
      "\030\001 \001(\t\022\022\n\nstart_date\030\002 \001(\t\022\020\n\010end_date\030\003" +
      " \001(\t\022\017\n\007w_train\030\004 \001(\005\022\013\n\003wa1\030\005 \001(\005\022\013\n\003wa" +
      "2\030\006 \001(\005\022\013\n\003wa3\030\007 \001(\005\022\r\n\005thrsh\030\010 \001(\005\022\021\n\tc" +
      "p_starts\030\t \003(\t\022\017\n\007cp_ends\030\n \003(\t\"%\n\023CPDet" +
      "ectionResponse\022\016\n\006result\030\001 \001(\t\"O\n\023Extrac" +
      "tRainsRequest\022\022\n\ndataset_id\030\001 \001(\t\022\022\n\nsta" +
      "rt_date\030\002 \001(\t\022\020\n\010end_date\030\003 \001(\t\"&\n\024Extra" +
      "ctRainsResponse\022\016\n\006result\030\001 \001(\t\"\246\001\n\032Calc" +
      "ulatePowerIndexRequest\022\022\n\ndataset_id\030\001 \001" +
      "(\t\022\022\n\nstart_date\030\002 \001(\t\022\020\n\010end_date\030\003 \001(\t" +
      "\022\023\n\013weeks_train\030\004 \001(\005\022\021\n\tcp_starts\030\005 \003(\t" +
      "\022\017\n\007cp_ends\030\006 \003(\t\022\025\n\rquery_modelar\030\007 \001(\010" +
      "\"-\n\033CalculatePowerIndexResponse\022\016\n\006resul" +
      "t\030\001 \001(\t\"\211\001\n\022ForecastingRequest\022\022\n\ndatase" +
      "t_id\030\001 \001(\t\022\022\n\nstart_date\030\002 \001(\t\022\020\n\010end_da" +
      "te\030\003 \001(\t\022\014\n\004lags\030\004 \001(\005\022\024\n\014future_steps\030\005" +
      " \001(\005\022\025\n\rquery_modelar\030\006 \001(\010\"\'\n\023Forecasti" +
      "ngResponse\022\020\n\010filename\030\001 \001(\t\"\201\001\n\036Estimat" +
      "eYawMisalignmentRequest\022\022\n\ndataset_id\030\001 " +
      "\001(\t\022\022\n\nstart_date\030\002 \001(\t\022\020\n\010end_date\030\003 \001(" +
      "\t\022\016\n\006window\030\004 \001(\005\022\025\n\rquery_modelar\030\005 \001(\010" +
      "\"1\n\037EstimateYawMisalignmentResponse\022\016\n\006r" +
      "esult\030\001 \001(\t\"]\n\016FrechetRequest\022\022\n\nstart_d" +
      "ate\030\001 \001(\t\022\020\n\010end_date\030\002 \001(\t\022\t\n\001i\030\003 \001(\t\022\017" +
      "\n\007DS_list\030\004 \001(\t\022\t\n\001R\030\005 \001(\t\"!\n\017FrechetRes" +
      "ponse\022\016\n\006result\030\001 \001(\t2\214\004\n\013DataService\022>\n" +
      "\016GetDatasetData\022\026.GetDatasetDataRequest\032" +
      "\024.DatasetDataResponse\022.\n\013CheckWashes\022\016.W" +
      "ashesRequest\032\017.WashesResponse\0228\n\013CPDetec" +
      "tion\022\023.CPDetectionRequest\032\024.CPDetectionR" +
      "esponse\022;\n\014ExtractRains\022\024.ExtractRainsRe" +
      "quest\032\025.ExtractRainsResponse\022P\n\023Calculat" +
      "ePowerIndex\022\033.CalculatePowerIndexRequest" +
      "\032\034.CalculatePowerIndexResponse\0228\n\013Foreca" +
      "sting\022\023.ForecastingRequest\032\024.Forecasting" +
      "Response\022\\\n\027EstimateYawMisalignment\022\037.Es" +
      "timateYawMisalignmentRequest\032 .EstimateY" +
      "awMisalignmentResponse\022,\n\007Frechet\022\017.Frec" +
      "hetRequest\032\020.FrechetResponseB@\n1eu.more2" +
      "020.visual.domain.GrpcAutoGenerated.tool" +
      "sB\tGrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetDatasetDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetDatasetDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetDatasetDataRequest_descriptor,
        new java.lang.String[] { "DataId", });
    internal_static_DatasetDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DatasetDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DatasetDataResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_WashesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WashesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WashesRequest_descriptor,
        new java.lang.String[] { "DatasetId", });
    internal_static_WashesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WashesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WashesResponse_descriptor,
        new java.lang.String[] { "Washes", });
    internal_static_CPDetectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CPDetectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CPDetectionRequest_descriptor,
        new java.lang.String[] { "DatasetId", "StartDate", "EndDate", "WTrain", "Wa1", "Wa2", "Wa3", "Thrsh", "CpStarts", "CpEnds", });
    internal_static_CPDetectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CPDetectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CPDetectionResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_ExtractRainsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ExtractRainsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExtractRainsRequest_descriptor,
        new java.lang.String[] { "DatasetId", "StartDate", "EndDate", });
    internal_static_ExtractRainsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ExtractRainsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExtractRainsResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_CalculatePowerIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CalculatePowerIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculatePowerIndexRequest_descriptor,
        new java.lang.String[] { "DatasetId", "StartDate", "EndDate", "WeeksTrain", "CpStarts", "CpEnds", "QueryModelar", });
    internal_static_CalculatePowerIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CalculatePowerIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculatePowerIndexResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_ForecastingRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ForecastingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForecastingRequest_descriptor,
        new java.lang.String[] { "DatasetId", "StartDate", "EndDate", "Lags", "FutureSteps", "QueryModelar", });
    internal_static_ForecastingResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ForecastingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForecastingResponse_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_EstimateYawMisalignmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_EstimateYawMisalignmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EstimateYawMisalignmentRequest_descriptor,
        new java.lang.String[] { "DatasetId", "StartDate", "EndDate", "Window", "QueryModelar", });
    internal_static_EstimateYawMisalignmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_EstimateYawMisalignmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EstimateYawMisalignmentResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_FrechetRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_FrechetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FrechetRequest_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "I", "DSList", "R", });
    internal_static_FrechetResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_FrechetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FrechetResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
