// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tools.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.tools;

public interface WashesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.WashesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string washes = 1;</code>
   */
  java.lang.String getWashes();
  /**
   * <code>string washes = 1;</code>
   */
  com.google.protobuf.ByteString
      getWashesBytes();
}
