// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: athForecasting.proto

package eu.more2020.visual.domain.GrpcAutoGenerated.AthenaForecasting;

public final class AthForecasting {
  private AthForecasting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myservice_HandleDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myservice_HandleDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myservice_HandleDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myservice_HandleDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myservice_HandleDataResponse_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myservice_HandleDataResponse_ResultsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024athForecasting.proto\022\tmyservice\"_\n\021Han" +
      "dleDataRequest\022\017\n\007data_id\030\001 \001(\t\022\022\n\nstart" +
      "_date\030\002 \001(\t\022\020\n\010end_date\030\003 \001(\t\022\023\n\013use_cas" +
      "e_id\030\004 \001(\t\"\201\001\n\022HandleDataResponse\022;\n\007res" +
      "ults\030\001 \003(\0132*.myservice.HandleDataRespons" +
      "e.ResultsEntry\032.\n\014ResultsEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\002:\0028\0012X\n\tMyService\022K\n\nH" +
      "andleData\022\034.myservice.HandleDataRequest\032" +
      "\035.myservice.HandleDataResponse\"\000BA\n=eu.m" +
      "ore2020.visual.domain.GrpcAutoGenerated." +
      "AthenaForecastingP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_myservice_HandleDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_myservice_HandleDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myservice_HandleDataRequest_descriptor,
        new java.lang.String[] { "DataId", "StartDate", "EndDate", "UseCaseId", });
    internal_static_myservice_HandleDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_myservice_HandleDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myservice_HandleDataResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_myservice_HandleDataResponse_ResultsEntry_descriptor =
      internal_static_myservice_HandleDataResponse_descriptor.getNestedTypes().get(0);
    internal_static_myservice_HandleDataResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myservice_HandleDataResponse_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
